# Actividad 3

## Mauricio López Coronado

# Ejercicio 1
Toma el archivo datosCT.xlsx, 
calcula la Utilid, )
encuentra el promedio de Gastos en los meses que la Utilidad fue negat y va
encuentra los ingresos totales del año


In [8]:
import pandas as pd

### 1.- Encontrar la utilidad

In [112]:
datos["Utilidad"] = datos["Ingreso"] - datos["Gasto"]
datos

Unnamed: 0  Ingreso  Gasto  Utilidad
0        Enero     1340   1880      -540
1      Febrero     2590   3130      -540
2        Marzo     3570   2140      1430
3        Abril     4450   3370      1080
4         Mayo     1330   2990     -1660
5        Junio     1610   1970      -360
6        Julio     1500   2230      -730
7       Agosto     2270   1240      1030
8   Septiembre     1910   1470       440
9      Octubre     2120   2280      -160
10   Noviembre     3950   1870      2080
11   Diciembre     1380   3140     -1760

### 2.- Promedio de gastos en los meses en que la utilidad fue negativa

In [114]:
datosneg = datos[datos["Utilidad"]<15]


In [120]:
np.mean(datosneg["Gasto"])

2517.1428571428573

### 3.- Ingresos totales anuales

In [99]:
datos = pd.read_excel("datosCT.xlsx")
datos

Unnamed: 0  Ingreso  Gasto
0        Enero     1340   1880
1      Febrero     2590   3130
2        Marzo     3570   2140
3        Abril     4450   3370
4         Mayo     1330   2990
5        Junio     1610   1970
6        Julio     1500   2230
7       Agosto     2270   1240
8   Septiembre     1910   1470
9      Octubre     2120   2280
10   Noviembre     3950   1870
11   Diciembre     1380   3140

In [101]:
Suma = datos["Ingreso"].sum()

In [103]:
print("El ingreso total anual es:", Suma)

El ingreso total anual es: 28020


# Ejercicio 2
Crea estructuras usando Numpy y obten AB

In [30]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[2], [4]])

In [32]:
A

array([[1, 2],
       [3, 4]])

In [34]:
B

array([[2],
       [4]])

In [36]:
A * B

array([[ 2,  4],
       [12, 16]])

In [38]:
A @ B

array([[10],
       [22]])